# ./docker-compose.yml

version: '3'

services:
  db:
    build: ./database
    image: puneethk26/eventsdb:latest
    ports:
      - "3306:3306"
  events:
    build: .
    image: puneethk26/eventsweb:latest
    restart: always
    container_name: events
    depends_on:
      - db
    ports:
      - "4000:4000"
    environment:
     - DATABASE_HOST=db
    stdin_open: true
    tty: true
