# ./docker-compose.yml

version: '3'

services:
  db:
    build: ./database
    image: puneethk26/eventsdb:latest
    ports:
      - "3306:3306"
  events:
    build: .
    image: puneethk26/eventsweb:latest
    container_name: events
    depends_on:
      - db
    ports:
      - "4000:4000"
    environment:
     - DATABASE_HOST=db
    # command: ["./run.sh", "db:3306"]
    stdin_open: true
    tty: true

    # environment:
    #   DATABASE__CLIENT: mysql
    #   DATABASE__CONNECTION__HOST: mysql
    #   DATABASE__CONNECTION__USER: root
    #   DATABASE__CONNECTION__PASSWORD:
    # depends_on:
    #   - mysql:5.7
